### ISSUE TITLE
Typo in energy balance?

### ISSUE THREAD

**Issue by timokoch** [Simulation-Benchmarks/11thSPE-CSP#13]
The energy balance is currently

<img width="442" alt="Screenshot 2023-07-22 at 22 51 41" src="https://github.com/Simulation-Benchmarks/11thSPE-CSP/assets/19410784/b1673ec0-6480-48f3-bd2e-ee2da58caab1">

but since the solid velocity is assumed zero, no gravity terms should be added in the storage term for the solid. (The term comes from the gravitational work $\phi s_\alpha\rho_\alpha \boldsymbol{g}\cdot\boldsymbol{u}_\alpha$ which vanishes for the solid.)

**Comment by berndflemisch** [comment]
Sounds right, let's ping @JMNordbotten for confirmation.

**Comment by JMNordbotten** [comment]
I am not sure this matters?  Since we do not include deformation in the model, then all terms multiplying gravity are constants for the solid, thus the time-derivative is already zero.

**Comment by timokoch** [comment]
ok, I agree it doesn't matter in this particular setup when $\rho_s$ is a constant and $s_s = \frac{1-\phi}{\phi}$. Just looks wrong but isn't wrong.
