### ISSUE TITLE
Definitions of Rs and Rv in terms of component mass fractions

### ISSUE THREAD

**Issue by FredrikSaaf** [Simulation-Benchmarks/11thSPE-CSP#21]
https://github.com/Simulation-Benchmarks/11thSPE-CSP/blob/a566536b43f0a8e33ce218c64bd1222ab95c9f98/thermodynamics/writeFluidFlowerPROPS.m#L101

I think we should write Rs = (xCO2/xH2O)*(rhoOS/rhoGS) and not Rs = xCO2*(rhoOS/rhoGS) (where xCO2 = fraction CO2 in water, xH2O = fraction H2O in water, rhoOS = stock-tank density of water, rhoGS = stock-tank density of CO2). 

We would expect that if xg->1 we should have Rs-> infinity. Probably the difference is not great in practice since xo is close to 1.

**Comment by moyner** [comment]
Hi, that's a good question. My understanding is that Rs is normally defined relative to the volume of liberated gas at surface/stock tank conditions when the resident phase (made up of both CO2 and H2O) is brought to those conditions. The expression uses the maximum dissolvable CO2 at that pressure.

I think that a description where a liquid phase is entirely made up of the light component is not feasible for a Rs/Rv description. It always assumes that a ratio between liquid and vapor phases at surface conditions can be defined for all possible compositions in the reservoir.

**Comment by FredrikSaaf** [comment]
Hi, thanks for your reply. I agree that the reservoir phase would not be made up purely of one component in practical situations. In the case we are interested in here, the water phase at reservoir conditions would have mass-fractions xCO2+xH2O=1, where xCO2 would be smaller, and xH2O would be larger/close to 1.

As I think we agree, the definition of Rs in black oil framework (bringing reservoir oil at (P,T) to standard conditions) is: 

Rs = (surface volume of gas from reservoir oil) / (surface volume of oil from reservoir oil). 

The components in the reservoir phase (usually denoted Heavy and Light) are assumed to exactly correspond to the stock tank "oil" and "gas" fluids. If we apply the same reasoning to a reservoir "Water" phase with surface components H2O and CO2 then we arrive at the expression I mentioned.

**Comment by FredrikSaaf** [comment]
Happy to contribute in a small way! Your scripts will be a great help to the community in getting PVT properties set up in a consistent/accurate manner.

**Comment by moyner** [comment]
The fixed version is merged now. The effect was more pronounced than I expected on the PVT tables.

**Comment by berndflemisch** [comment]
Fixed by #22, thanks!
