### ISSUE TITLE
CO2 solubility behavior at high pressures 

### ISSUE THREAD

**Issue by GiacomoRivolta** [Simulation-Benchmarks/11thSPE-CSP#28]
Hi,
I'm looking a bit into the script `make_solubility_table.py` and I tried to compare the results obtained from the script with experimental results available in literature and reported in Spycher, Pruess and Ennis-King, 2003.
For example, the behavior for CO2 solubility at 50°C seems to differ with what report in the paper, expecially in the region above 400 bar (see figures below: first one from Spycher et al. 2003 and second one from me 😃).

![image](https://github.com/Simulation-Benchmarks/11thSPE-CSP/assets/79972966/b3a890b5-903b-4c6f-b219-b0144392e6eb)
![image](https://github.com/Simulation-Benchmarks/11thSPE-CSP/assets/79972966/0807bab8-aede-4031-b6af-420a703afa91)

As you can see the red triangles in the second figures tend to differ from the experimental results (blue dots) and show a decreasing trend in the high pressure region; this behavior it's not expected and it's not reproducing Spycher-Pruess-Ennis-King results. 
(Even if the pressure range is extended in my plot you can clearly see that the trend is not matching the paper results).

I tried looking in the code but I couldn't find nothing wrong, also comparing the equations with what is reported in the paper.

Could you take a look into it and give me some feedback (maybe it's something trivial)?

Thank you in advance for your time and effort,
ciao 👋!

**Comment by berndflemisch** [comment]
I hope that this is resolved by now, see also https://connect.spe.org/discussion/calculation-of-co2-solubility. Sorry for reacting so late.

**Comment by berndflemisch** [comment]
It would be great if you could double-check and eventually close the issue.

**Comment by GiacomoRivolta** [comment]
Yep, it's resolved now, tested it and working! Thank you for your effort 😄

**Comment by GiacomoRivolta** [comment]
Closing the issue, thank you again!
