### ISSUE TITLE
Scaling kg->t lacking in SPE11b visualization script

### ISSUE THREAD

**Issue by jwboth** [Simulation-Benchmarks/11thSPE-CSP#31]
In line 179 of evaluation/spe11b_visualize_spatial_maps.py, the total mass of CO2 should be scaled by 1e-3, if I am not mistaken.

**Comment by berndflemisch** [comment]
Thanks for noticing! It's fixed by https://github.com/Simulation-Benchmarks/11thSPE-CSP/commit/1b334ecb1af0fde194c3bc19cd860d9f787cf701.
