### ISSUE TITLE
AssertionError in make_spe11c_geo.py

### ISSUE THREAD

**Issue by cpgr** [Simulation-Benchmarks/11thSPE-CSP#5]
Hey @dglaeser - thanks for the gmsh files. I have hit a problem trying to make the 3D model though.

Running
```
python3 make_spe11c_geo.py --mesh-size 250
```
I hit an AssertionError
```
Info    : Reading 'spe11b.geo'...
Info    : Reading 'spe11a.geo'...
Info    : Done reading 'spe11a.geo'
Info    : Done reading 'spe11b.geo'
Reading entities & physical groups from the model
Defining new model using the OCC kernel
Adding points
Adding curves
Adding surfaces
Rotating model such that the surfaces align with the z-axis
Copying Surfaces to the back of the domain
Creating connecting surfaces and volumes
Traceback (most recent call last):
  File "/Users/gre462/Documents/Strategic Projects/SPE11/11thSPE-CSP/geometries/make_spe11c_geo.py", line 117, in <module>
    assert front_curve[1] > 0 and back_curve[1] > 0 \
AssertionError
```

**Comment by dglaeser** [comment]
Hi @cpgr, I'm sorry to hear the script does not work for you.. Could you quickly post here which gmsh version you are using? Unfortunately I cannot reproduce this error (I am using the gmsh python api v4.11.1)

**Comment by cpgr** [comment]
I was on 4.10.4, and after updating gmsh to 4.11.1 it now works!

**Comment by dglaeser** [comment]
@cpgr, thanks for your reply. It is unfortunate that this error appears with a fairly recent version of gmsh... I added a statement on this into the readme file in #6
